---
- name: Ensure the data directory exists
  become: true
  become_user: "{{ service_name }}"
  ansible.builtin.file:
    path: "{{ service_home }}/data"
    state: directory
    mode: '0755'

- name: Deploy the Quadlets
  ansible.builtin.import_role:
    name: quadlet_service
